Repository xmrig/xmrig, pull requests merged in 2019-12, with the labels that each got.

#1351 RandomX fixes
  src/App.cpp
  src/backend/common/Workers.cpp
  src/backend/cpu/CpuWorker.cpp
  src/crypto/randomx/aes_hash.cpp
  src/crypto/randomx/aes_hash.hpp
  src/crypto/randomx/intrin_portable.h
  src/crypto/randomx/jit_compiler_x86.cpp
  src/crypto/randomx/jit_compiler_x86.hpp
  src/crypto/randomx/randomx.cpp
  src/crypto/randomx/randomx.h
  src/crypto/randomx/virtual_machine.cpp
  src/crypto/randomx/virtual_machine.hpp
Labels: bug, enhancement

#1388 1GB hugepages support for Linux
  src/Summary.cpp
  src/backend/common/interfaces/IRxStorage.h
  src/backend/cpu/CpuConfig.cpp
  src/backend/cpu/CpuConfig.h
  src/backend/cpu/interfaces/ICpuInfo.h
  src/backend/cpu/platform/BasicCpuInfo.cpp
  src/backend/cpu/platform/BasicCpuInfo.h
  src/config.json
  src/core/Miner.cpp
  src/crypto/common/VirtualMemory.h
  src/crypto/common/VirtualMemory_unix.cpp
  src/crypto/common/VirtualMemory_win.cpp
  src/crypto/randomx/allocator.cpp
  src/crypto/randomx/allocator.hpp
  src/crypto/randomx/randomx.cpp
  src/crypto/randomx/randomx.h
  src/crypto/randomx/virtual_memory.cpp
  src/crypto/randomx/virtual_memory.hpp
  src/crypto/rx/Rx.cpp
  src/crypto/rx/Rx.h
  src/crypto/rx/RxBasicStorage.cpp
  src/crypto/rx/RxBasicStorage.h
  src/crypto/rx/RxDataset.cpp
  src/crypto/rx/RxDataset.h
  src/crypto/rx/RxNUMAStorage.cpp
  src/crypto/rx/RxNUMAStorage.h
  src/crypto/rx/RxQueue.cpp
  src/crypto/rx/RxQueue.h
Labels: enhancement

#1414 MSR mod for Windows
  cmake/randomx.cmake
  src/crypto/rx/Rx.cpp
  src/crypto/rx/Rx_windows.cpp
Labels: enhancement

#1418 increase stratum send buffer size
  src/base/net/stratum/Client.h
Labels: bug

#1434 RandomSFX (Safex Cash variant) support
  src/backend/opencl/cl/cn/algorithm.cl
  src/backend/opencl/runners/OclRxBaseRunner.cpp
  src/crypto/common/Algorithm.cpp
  src/crypto/common/Algorithm.h
  src/crypto/randomx/randomx.cpp
  src/crypto/randomx/randomx.h
  src/crypto/rx/RxAlgo.cpp
Labels: enhancement

#1445 Add MoneroV (rx/v) algorithm [based on MoneroOcean/master]
  src/backend/opencl/cl/cn/algorithm.cl
  src/backend/opencl/cl/rx/randomx.cl
  src/backend/opencl/cl/rx/randomx_constants_v.h
  src/crypto/common/Algorithm.cpp
  src/crypto/common/Algorithm.h
  src/crypto/randomx/randomx.cpp
  src/crypto/randomx/randomx.h
  src/crypto/rx/RxAlgo.cpp
Labels: algo

#1473 Auto-config for mobile Ryzen APUs
  src/backend/opencl/generators/ocl_generic_rx_generator.cpp
  src/backend/opencl/runners/OclRxBaseRunner.cpp
Labels: opencl

#1477 Refactor Ryzen fix to fix compilation issues
  src/crypto/randomx/jit_compiler_x86.cpp
  src/crypto/randomx/jit_compiler_x86.hpp
  src/crypto/rx/Rx.h
  src/crypto/rx/Rx_linux.cpp
  src/crypto/rx/Rx_win.cpp
Labels: bug
