Repository xmrig/xmrig, pull requests merged in 2020-07, with the labels that each got.

#1760 KawPow: fixed rare duplicate share errors
  src/backend/common/WorkerJob.h
Labels: bug, kawpow

#1763 KawPow: fixed more duplicate share errors
  src/backend/common/WorkerJob.h
Labels: bug, kawpow

#1766 RandomX: tweaked Ryzen code
  src/crypto/randomx/asm/program_read_dataset_ryzen.inc
  src/crypto/randomx/randomx.h
Labels: randomx

#1771 Adopt new SSE2NEON and reduce ARM-specific changes
  src/crypto/cn/CryptoNight_arm.h
  src/crypto/cn/SSE2NEON.h
  src/crypto/cn/soft_aes.h
  src/crypto/cn/sse2neon.h
Labels: arm

#1774 RandomX: added cache QoS support
  src/backend/cpu/interfaces/ICpuInfo.h
  src/backend/cpu/platform/BasicCpuInfo.cpp
  src/backend/cpu/platform/BasicCpuInfo.h
  src/config.json
  src/crypto/rx/Rx.cpp
  src/crypto/rx/Rx.h
  src/crypto/rx/RxConfig.cpp
  src/crypto/rx/RxConfig.h
  src/crypto/rx/Rx_linux.cpp
  src/crypto/rx/Rx_win.cpp
Labels: enhancement, randomx

#1780 Cryptonight OpenCL: fix for long input data
  src/backend/opencl/cl/cn/cryptonight.cl
  src/backend/opencl/cl/cn/cryptonight_cl.h
  src/backend/opencl/kernels/Cn0Kernel.cpp
  src/backend/opencl/kernels/Cn0Kernel.h
  src/backend/opencl/runners/OclCnRunner.cpp
  src/base/net/stratum/Job.h
Labels: algo, opencl

#1777 Increased max blob size to support Haven offshore capability
  src/base/net/stratum/Job.h
Labels: algo

#1786 Added mining on battery setting
  src/base/kernel/Platform.h
  src/base/kernel/Platform_mac.cpp
  src/base/kernel/Platform_unix.cpp
  src/base/kernel/Platform_win.cpp
  src/base/kernel/config/BaseConfig.cpp
  src/base/kernel/config/BaseConfig.h
  src/config.json
  src/core/Miner.cpp
  src/core/config/Config.cpp
  src/core/config/Config_default.h
Labels: enhancement

#1794 More robust 1 GB pages handling
  src/backend/cpu/CpuWorker.cpp
  src/crypto/common/VirtualMemory.cpp
  src/crypto/common/VirtualMemory.h
  src/crypto/common/VirtualMemory_unix.cpp
  src/crypto/rx/RxDataset.cpp
  src/crypto/rx/RxDataset.h
Labels: enhancement
