Repository xmrig/xmrig, pull requests merged in 2020-03, with the labels that each got.

#1573 AstroBWT algorithm (DERO) support
  CMakeLists.txt
  cmake/astrobwt.cmake
  src/backend/cpu/CpuConfig.cpp
  src/backend/cpu/CpuConfig_gen.h
  src/backend/cpu/CpuWorker.cpp
  src/backend/cpu/platform/AdvancedCpuInfo.cpp
  src/backend/cpu/platform/BasicCpuInfo.cpp
  src/backend/cpu/platform/HwlocCpuInfo.cpp
  src/backend/opencl/cl/cn/algorithm.cl
  src/base/net/http/HttpClient.cpp
  src/base/net/stratum/DaemonClient.cpp
  src/base/net/stratum/DaemonClient.h
  src/crypto/astrobwt/AstroBWT.cpp
  src/crypto/astrobwt/AstroBWT.h
  src/crypto/astrobwt/Salsa20.cpp
  src/crypto/astrobwt/Salsa20.hpp
  src/crypto/astrobwt/salsa20_ref/ecrypt-config.h
  src/crypto/astrobwt/salsa20_ref/ecrypt-machine.h
  src/crypto/astrobwt/salsa20_ref/ecrypt-portable.h
  src/crypto/astrobwt/salsa20_ref/ecrypt-sync.h
  src/crypto/astrobwt/salsa20_ref/salsa20.c
  src/crypto/astrobwt/sha3.cpp
  src/crypto/astrobwt/sha3.h
  src/crypto/cn/CnHash.cpp
  src/crypto/cn/CryptoNight_test.h
  src/crypto/common/Algorithm.cpp
  src/crypto/common/Algorithm.h
  src/crypto/common/Coin.cpp
  src/crypto/common/Coin.h
Labels: algo, enhancement

#1575 Fixed new block detection for Dero solo mining
  src/base/net/stratum/DaemonClient.cpp
Labels: bug

#1580 AstroBWT 20-50% speedup
  src/backend/cpu/CpuBackend.cpp
  src/backend/cpu/CpuConfig.cpp
  src/backend/cpu/CpuConfig.h
  src/backend/cpu/CpuLaunchData.cpp
  src/backend/cpu/CpuLaunchData.h
  src/backend/cpu/CpuWorker.cpp
  src/backend/cpu/CpuWorker.h
  src/config.json
  src/core/config/Config_default.h
  src/crypto/astrobwt/AstroBWT.cpp
  src/crypto/astrobwt/AstroBWT.h
Labels: algo, enhancement

#1584 Fixed invalid AstroBWT hashes after algo switching
  src/crypto/astrobwt/AstroBWT.cpp
Labels: bug

#1578 Please add RandomX variant for Keva.
  scripts/generate_cl.js
  src/backend/cpu/CpuConfig_gen.h
  src/backend/cuda/CudaConfig_gen.h
  src/backend/opencl/cl/cn/algorithm.cl
  src/backend/opencl/cl/rx/randomx.cl
  src/backend/opencl/cl/rx/randomx_cl.h
  src/backend/opencl/cl/rx/randomx_constants_keva.h
  src/crypto/common/Algorithm.cpp
  src/crypto/common/Algorithm.h
  src/crypto/randomx/randomx.cpp
  src/crypto/randomx/randomx.h
  src/crypto/rx/RxAlgo.cpp
Labels: algo, randomx

#1590 Activate MSR mod only for RandomX algorithms
  src/crypto/rx/Rx.cpp
Labels: bug, enhancement

#1592 AVX2 optimized code for AstroBWT
  cmake/astrobwt.cmake
  src/backend/cpu/CpuConfig.cpp
  src/backend/cpu/CpuConfig.h
  src/backend/cpu/CpuLaunchData.cpp
  src/backend/cpu/CpuLaunchData.h
  src/backend/cpu/CpuWorker.cpp
  src/backend/cpu/CpuWorker.h
  src/core/Miner.cpp
  src/crypto/astrobwt/AstroBWT.cpp
  src/crypto/astrobwt/AstroBWT.h
  src/crypto/astrobwt/sha3_256_avx2.S
  src/crypto/astrobwt/sha3_256_avx2.asm
  src/crypto/astrobwt/sha3_256_avx2.inc
  src/crypto/astrobwt/sha3_256_keccakf1600_avx2.inc
Labels: algo, enhancement

#1605 Fixed AstroBWT OpenCL for NVIDIA GPUs
  src/backend/opencl/cl/astrobwt/BWT.cl
  src/backend/opencl/cl/astrobwt/astrobwt_cl.h
Labels: opencl
