Repository xmrig/xmrig, pull requests merged in 2020-11, with the labels that each got.

#1925 Add checking for config files in user home directory
  src/base/kernel/Base.cpp
Labels: enhancement

#1926 Fix compilation on ARMv8 with GCC 9.3.0
  src/crypto/rx/RxDataset.cpp
Labels: arm, bug

#1932 New MSR mod for Ryzen
  src/crypto/rx/RxConfig.cpp
Labels: randomx

#1935 Separate MSR mod for Zen/Zen2 and Zen3
  src/backend/cpu/interfaces/ICpuInfo.h
  src/backend/cpu/platform/BasicCpuInfo.cpp
  src/crypto/rx/RxConfig.cpp
Labels: randomx

#1939 CompiledVm: define default constructor
  src/crypto/randomx/vm_compiled.hpp
Labels: bug

#1941 Added CPUID info to JSON report
  src/backend/cpu/platform/BasicCpuInfo.cpp
  src/backend/cpu/platform/BasicCpuInfo.h
Labels: enhancement

#1942 MemoryPool: fix alignment modification
  src/crypto/common/MemoryPool.cpp
Labels: bug

#1944 Update randomx_boost.sh
  scripts/randomx_boost.sh
Labels: randomx

#1946 Fixed MSR mod names in JSON API
  src/backend/cpu/interfaces/ICpuInfo.h
  src/backend/cpu/platform/BasicCpuInfo.cpp
  src/crypto/rx/RxConfig.cpp
Labels: bug

#1960 Fix RandomX init when switching to other algo and back
  src/crypto/rx/Rx.cpp
Labels: bug
