Repository xmrig/xmrig, pull requests merged in 2020-10, with the labels that each got.

#1861 Fix ARM build - Blake2 without SSE, WITH_SSE cmake option
  CMakeLists.txt
  cmake/randomx.cmake
  doc/build/CMAKE_OPTIONS.md
Labels: arm, bug

#1862 RandomX: removed rx/loki
  scripts/generate_cl.js
  src/backend/opencl/cl/cn/algorithm.cl
  src/backend/opencl/cl/cn/cryptonight_cl.h
  src/backend/opencl/cl/rx/randomx.cl
  src/backend/opencl/cl/rx/randomx_cl.h
  src/backend/opencl/cl/rx/randomx_constants_loki.h
  src/base/crypto/Algorithm.cpp
  src/base/crypto/Algorithm.h
  src/crypto/randomx/configuration.h
  src/crypto/randomx/randomx.cpp
  src/crypto/randomx/randomx.h
  src/crypto/rx/RxAlgo.cpp
Labels: randomx

#1872 RxVm: fix randomx_create_vm call
  src/crypto/rx/RxVm.cpp
Labels: bug

#1875 RandomX: align args
  src/backend/cpu/CpuWorker.cpp
  src/backend/cpu/CpuWorker.h
  src/crypto/randomx/aes_hash.cpp
  src/net/JobResults.cpp
Labels: bug

#1890 Added argon2/chukwav2 algorithm
  src/backend/cpu/CpuConfig_gen.h
  src/backend/cpu/CpuWorker.cpp
  src/backend/opencl/cl/cn/algorithm.cl
  src/backend/opencl/cl/cn/cryptonight_cl.h
  src/backend/opencl/cl/rx/randomx_cl.h
  src/base/crypto/Algorithm.cpp
  src/base/crypto/Algorithm.h
  src/crypto/argon2/Hash.h
  src/crypto/cn/CnHash.cpp
  src/crypto/cn/CryptoNight_test.h
Labels: algo, enhancement

#1889 uv: fix performance issue
  src/base/base.cmake
  src/base/io/Async.cpp
  src/base/io/Async.h
  src/crypto/rx/RxQueue.h
  src/net/JobResults.cpp
Labels: bug, libuv

#1893 LineReader: fix partial read
  src/base/net/tools/LineReader.cpp
Labels: bug

#1895 Added benchmark and stress test
  cmake/flags.cmake
  doc/BENCHMARK.md
  src/backend/common/Worker.h
  src/backend/common/WorkerJob.h
  src/backend/common/Workers.cpp
  src/backend/common/Workers.h
  src/backend/common/interfaces/IBackend.h
  src/backend/common/interfaces/IWorker.h
  src/backend/cpu/CpuBackend.cpp
  src/backend/cpu/CpuBackend.h
  src/backend/cpu/CpuWorker.cpp
  src/backend/cuda/CudaBackend.cpp
  src/backend/cuda/CudaBackend.h
  src/backend/opencl/OclBackend.cpp
  src/backend/opencl/OclBackend.h
  src/base/base.cmake
  src/base/kernel/config/BaseTransform.cpp
  src/base/kernel/interfaces/IConfig.h
  src/base/net/stratum/Job.cpp
  src/base/net/stratum/Job.h
  src/base/net/stratum/NullClient.cpp
  src/base/net/stratum/NullClient.h
  src/base/net/stratum/Pool.cpp
  src/base/net/stratum/Pool.h
  src/core/Miner.cpp
  src/core/config/Config_platform.h
  src/core/config/usage.h
  src/net/Network.cpp
Labels: enhancement

#1897 Benchmark: added more check hashes and a progress indicator
  doc/BENCHMARK.md
  src/backend/common/Workers.cpp
  src/base/net/stratum/Pool.cpp
  src/base/net/stratum/Pool.h
  src/core/Miner.cpp
  src/core/config/usage.h
Labels: enhancement

#1899 Make round size power of 2
  src/backend/cuda/CudaWorker.cpp
  src/backend/opencl/OclWorker.cpp
Labels: bug

#1900 Fixed roundSize() usage in OCL/CUDA
  src/backend/cuda/CudaWorker.cpp
  src/backend/opencl/OclWorker.cpp
Labels: bug

#1912 MSR: supress kernel module warning
  src/crypto/rx/Rx_linux.cpp
Labels: bug
