Repository xmrig/xmrig, pull requests merged in 2020-12, with the labels that each got.

#1968 Added virtual machine detection
  src/Summary.cpp
  src/backend/cpu/interfaces/ICpuInfo.h
  src/backend/cpu/platform/BasicCpuInfo.cpp
  src/backend/cpu/platform/BasicCpuInfo.h
Labels: enhancement

#1969 Fixed errors found by static analysis
  src/backend/common/WorkerJob.h
  src/backend/cpu/platform/HwlocCpuInfo.h
  src/backend/opencl/runners/OclAstroBWTRunner.cpp
  src/backend/opencl/runners/OclKawPowRunner.cpp
  src/base/crypto/keccak.cpp
  src/crypto/astrobwt/AstroBWT.cpp
  src/crypto/cn/r/CryptonightR_gen.cpp
  src/crypto/randomx/jit_compiler_x86.cpp
  src/crypto/randomx/superscalar.cpp
  src/net/JobResults.cpp
Labels: bug

#1970 More static analysis fixes
  src/3rdparty/fmt/format-inl.h
  src/backend/opencl/runners/tools/OclKawPow.cpp
  src/backend/opencl/wrappers/OclLib.cpp
  src/base/net/tools/LineReader.cpp
  src/base/tools/String.cpp
  src/crypto/common/VirtualMemory_win.cpp
  src/crypto/randomx/aes_hash.cpp
  src/crypto/randomx/dataset.hpp
  src/crypto/randomx/jit_compiler_x86.cpp
  src/crypto/randomx/jit_compiler_x86.hpp
  src/crypto/randomx/superscalar.cpp
  src/crypto/randomx/superscalar_program.hpp
  src/crypto/rx/RxQueue.cpp
  src/crypto/rx/Rx_linux.cpp
Labels: bug

#1986 Dataset initialization with AVX2 (faster startup)
  scripts/benchmark_10M.cmd
  scripts/benchmark_1M.cmd
  scripts/pool_mine_example.cmd
  scripts/solo_mine_example.cmd
  src/backend/common/Workers.cpp
  src/backend/cpu/interfaces/ICpuInfo.h
  src/backend/cpu/platform/BasicCpuInfo.cpp
  src/backend/cpu/platform/BasicCpuInfo.h
  src/config.json
  src/core/config/Config_default.h
  src/crypto/randomx/asm/program_sshash_avx2_constants.inc
  src/crypto/randomx/asm/program_sshash_avx2_epilogue.inc
  src/crypto/randomx/asm/program_sshash_avx2_loop_begin.inc
  src/crypto/randomx/asm/program_sshash_avx2_loop_end.inc
  src/crypto/randomx/asm/program_sshash_avx2_save_registers.inc
  src/crypto/randomx/asm/program_sshash_avx2_ssh_load.inc
  src/crypto/randomx/asm/program_sshash_avx2_ssh_prefetch.inc
  src/crypto/randomx/jit_compiler_a64.cpp
  src/crypto/randomx/jit_compiler_a64.hpp
  src/crypto/randomx/jit_compiler_fallback.cpp
  src/crypto/randomx/jit_compiler_fallback.hpp
  src/crypto/randomx/jit_compiler_x86.cpp
  src/crypto/randomx/jit_compiler_x86.hpp
  src/crypto/randomx/jit_compiler_x86_static.S
  src/crypto/randomx/jit_compiler_x86_static.asm
  src/crypto/randomx/jit_compiler_x86_static.hpp
  src/crypto/randomx/randomx.cpp
  src/crypto/randomx/randomx.h
  src/crypto/randomx/vm_compiled.hpp
  src/crypto/rx/Rx.cpp
  src/crypto/rx/RxConfig.cpp
  src/crypto/rx/RxConfig.h
  src/crypto/rx/RxDataset.cpp
Labels: enhancement, randomx

#1987 Another dataset AVX2 init speedup (+3.8% faster on Zen3)
  src/crypto/randomx/asm/program_sshash_avx2_epilogue.inc
  src/crypto/randomx/asm/program_sshash_avx2_loop_end.inc
  src/crypto/randomx/jit_compiler_x86.cpp
  src/crypto/randomx/jit_compiler_x86_static.S
  src/crypto/randomx/jit_compiler_x86_static.asm
Labels: randomx

#1989 Fixed broken Dero solo mining
  src/base/net/stratum/Job.cpp
Labels: bug

#1979 Don't use team 'x64' for '64-bit'
  src/Summary.cpp
  src/backend/cpu/interfaces/ICpuInfo.h
  src/backend/cpu/platform/BasicCpuInfo.cpp
  src/backend/cpu/platform/BasicCpuInfo_arm.cpp
Labels: bug

#1980 Fix build on GCC 11
  src/base/net/tools/MemPool.h
Labels: bug

#1998 Show hashrate in the benchmark finished message
  src/base/net/stratum/benchmark/BenchClient.cpp
Labels: enhancement

#2009 AstroBWT OpenCL fixes
  src/backend/opencl/OclWorker.cpp
  src/backend/opencl/cl/astrobwt/BWT.cl
  src/backend/opencl/cl/astrobwt/astrobwt_cl.h
  src/backend/opencl/runners/OclAstroBWTRunner.cpp
Labels: bug, opencl
