Repository xmrig/xmrig, pull requests merged in 2020-05, with the labels that each got.

#1668 Optimized RandomX dataset initialization
  cmake/randomx.cmake
  src/3rdparty/argon2/lib/core.c
  src/backend/cpu/CpuBackend.cpp
  src/crypto/randomx/argon2.h
  src/crypto/randomx/argon2_core.c
  src/crypto/randomx/argon2_core.h
  src/crypto/randomx/argon2_ref.c
  src/crypto/randomx/dataset.cpp
Labels: enhancement

#1675 Fix Windows include files cases
  cmake/OpenSSL.cmake
  src/backend/opencl/OclCache_win.cpp
  src/crypto/rx/Rx_win.cpp
Labels: bug

#1697 KawPow: tuned work group size for OpenCL
  src/backend/opencl/OclThread.cpp
  src/backend/opencl/OclThread.h
  src/backend/opencl/cl/kawpow/defs.h
  src/backend/opencl/cl/kawpow/kawpow.cl
  src/backend/opencl/cl/kawpow/kawpow_cl.h
  src/backend/opencl/cl/kawpow/kawpow_dag_cl.h
  src/backend/opencl/generators/ocl_generic_kawpow_generator.cpp
  src/backend/opencl/runners/OclKawPowRunner.cpp
  src/backend/opencl/runners/OclKawPowRunner.h
  src/backend/opencl/runners/tools/OclKawPow.cpp
  src/backend/opencl/runners/tools/OclKawPow.h
Labels: algo

#1698 KawPow performance fix for AMD Navi
  src/backend/opencl/cl/kawpow/kawpow.cl
  src/backend/opencl/cl/kawpow/kawpow_cl.h
Labels: algo

#1699 KawPow fix for retarted AMD OpenCL compiler
  src/backend/opencl/cl/kawpow/kawpow.cl
  src/backend/opencl/cl/kawpow/kawpow_cl.h
Labels: algo

#1700 Fixed hashrate and diff display for KawPow
  src/backend/common/Hashrate.cpp
  src/backend/cuda/CudaBackend.cpp
  src/backend/opencl/OclBackend.cpp
  src/core/Miner.cpp
  src/crypto/kawpow/KPCache.cpp
  src/crypto/kawpow/KPCache.h
  src/net/Network.cpp
Labels: algo
