Repository xmrig/xmrig, pull requests merged in 2021-08, with the labels that each got.

#2512 Show the number of transactions in pool job
  src/base/net/stratum/Job.cpp
  src/base/net/stratum/Job.h
  src/net/Network.cpp
Labels: enhancement

#2532 Refactoring: Stable (persistent) algorithms IDs.
  src/backend/common/Threads.cpp
  src/backend/common/Threads.h
  src/backend/cpu/CpuBackend.cpp
  src/backend/cpu/CpuBackend.h
  src/backend/cpu/CpuConfig_gen.h
  src/backend/cpu/platform/BasicCpuInfo.cpp
  src/backend/cpu/platform/HwlocCpuInfo.cpp
  src/backend/cuda/CudaConfig_gen.h
  src/backend/cuda/wrappers/CudaLib.cpp
  src/backend/cuda/wrappers/CudaLib.h
  src/backend/opencl/OclConfig_gen.h
  src/backend/opencl/cl/cn/algorithm.cl
  src/backend/opencl/cl/cn/cryptonight_cl.h
  src/backend/opencl/cl/rx/randomx_cl.h
  src/backend/opencl/generators/ocl_generic_cn_generator.cpp
  src/backend/opencl/generators/ocl_vega_cn_generator.cpp
  src/backend/opencl/runners/OclCnRunner.cpp
  src/backend/opencl/runners/OclCnRunner.h
  src/base/base.cmake
  src/base/crypto/Algorithm.cpp
  src/base/crypto/Algorithm.h
  src/base/net/stratum/Client.cpp
  src/base/net/stratum/Client.h
  src/base/net/stratum/EthStratumClient.cpp
  src/base/net/stratum/EthStratumClient.h
  src/base/net/stratum/NetworkState.cpp
  src/base/net/stratum/NetworkState.h
  src/base/net/stratum/Pool.cpp
  src/base/net/stratum/Pool.h
  src/base/net/stratum/benchmark/BenchClient.cpp
  src/core/Miner.cpp
  src/core/Miner.h
  src/crypto/cn/CnAlgo.h
  src/crypto/cn/CnHash.cpp
  src/crypto/cn/CnHash.h
  src/crypto/rx/Rx.cpp
  src/crypto/rx/RxQueue.cpp
  src/crypto/rx/RxQueue.h
  src/donate.h
  src/net/Network.cpp
  src/net/Network.h
  src/net/strategies/DonateStrategy.cpp
  src/net/strategies/DonateStrategy.h
  src/xmrig.cpp
Labels: enhancement

#2537 Fixed Termux build
  src/base/net/stratum/DaemonClient.cpp
  src/crypto/cn/CnHash.cpp
  src/crypto/cn/CnHash.h
Labels: bug, arm

#2548 Added automatic coin detection for daemon mining
  src/base/crypto/Coin.cpp
  src/base/crypto/Coin.h
  src/base/kernel/interfaces/IClient.h
  src/base/net/stratum/BaseClient.cpp
  src/base/net/stratum/BaseClient.h
  src/base/net/stratum/DaemonClient.cpp
  src/base/net/stratum/DaemonClient.h
  src/base/net/stratum/Pool.cpp
  src/base/tools/cryptonote/BlobReader.h
  src/base/tools/cryptonote/BlockTemplate.cpp
  src/base/tools/cryptonote/BlockTemplate.h
  src/base/tools/cryptonote/WalletAddress.cpp
  src/base/tools/cryptonote/WalletAddress.h
Labels: enhancement

#2565 AstroBWT: add AVX2 Salsa20 implementation
  cmake/astrobwt.cmake
  src/crypto/astrobwt/AstroBWT.cpp
  src/crypto/astrobwt/xmm6int/salsa20_xmm6int-avx2.c
  src/crypto/astrobwt/xmm6int/u0.h
  src/crypto/astrobwt/xmm6int/u1.h
  src/crypto/astrobwt/xmm6int/u4.h
  src/crypto/astrobwt/xmm6int/u8.h
Labels: enhancement, algo
