Repository xmrig/xmrig, pull requests merged in 2021-02, with the labels that each got.

#2075 Fixed crashes on ARM
  src/crypto/randomx/jit_compiler_a64.cpp
  src/crypto/rx/RxConfig.h
Labels: arm, bug

#2076 Added support for flexible huge page sizes on Linux.
  src/backend/cpu/CpuConfig.cpp
  src/backend/cpu/CpuConfig.h
  src/base/kernel/interfaces/IConfig.h
  src/core/Controller.cpp
  src/core/config/ConfigTransform.cpp
  src/core/config/Config_platform.h
  src/core/config/usage.h
  src/crypto/common/HugePagesInfo.cpp
  src/crypto/common/HugePagesInfo.h
  src/crypto/common/LinuxMemory.cpp
  src/crypto/common/LinuxMemory.h
  src/crypto/common/VirtualMemory.cpp
  src/crypto/common/VirtualMemory.h
  src/crypto/common/VirtualMemory_unix.cpp
  src/crypto/common/VirtualMemory_win.cpp
Labels: enhancement

#2077 Fix for illegal instruction crash on ARM
  src/crypto/randomx/jit_compiler_a64.cpp
Labels: bug

#2080 Fix compile error in Termux
  src/crypto/common/VirtualMemory_unix.cpp
Labels: bug

#2089 Optimized cn-heavy for Zen3
  src/backend/cpu/CpuBackend.cpp
  src/backend/cpu/CpuConfig.cpp
  src/backend/cpu/CpuWorker.cpp
  src/backend/cpu/platform/HwlocCpuInfo.cpp
  src/crypto/cn/CnHash.cpp
  src/crypto/cn/CryptoNight_arm.h
  src/crypto/cn/CryptoNight_x86.h
  src/crypto/rx/Rx.cpp
Labels: algo, enhancement

#2104 Added `pause-on-active` option
  src/base/kernel/Platform.h
  src/base/kernel/Platform_unix.cpp
  src/base/kernel/Platform_win.cpp
  src/base/kernel/config/BaseConfig.cpp
  src/base/kernel/config/BaseConfig.h
  src/base/kernel/config/BaseTransform.cpp
  src/base/kernel/interfaces/IConfig.h
  src/config.json
  src/core/Miner.cpp
  src/core/config/Config.cpp
  src/core/config/Config_default.h
  src/core/config/Config_platform.h
  src/core/config/usage.h
Labels: enhancement

#2117 Fixed crash when GPU mining cn-heavy on Zen3 system
  src/backend/cpu/CpuWorker.cpp
  src/crypto/cn/CnHash.cpp
Labels: bug

#2122 Fixed pause logic when both pause on battery and user activity are en…
  src/core/Miner.cpp
Labels: bug
