Repository xmrig/xmrig, pull requests merged in 2021-12, with the labels that each got.

#2769 Performance fixes
  CHANGELOG.md
  src/backend/cpu/CpuWorker.h
  src/backend/cpu/platform/BasicCpuInfo.cpp
  src/base/net/stratum/benchmark/BenchClient.cpp
  src/crypto/cn/CnHash.cpp
  src/crypto/cn/CryptoNight.h
  src/crypto/cn/CryptoNight_monero.h
  src/crypto/cn/CryptoNight_x86.h
  src/crypto/cn/CryptoNight_x86_vaes.cpp
  src/crypto/cn/CryptoNight_x86_vaes.h
  src/crypto/cn/asm/cn1/cnv1_double_main_loop.inc
  src/crypto/cn/asm/cn1/cnv1_quad_main_loop.inc
  src/crypto/cn/asm/cn1/cnv1_single_main_loop.inc
  src/crypto/cn/asm/cn_main_loop.S
  src/crypto/cn/asm/cn_main_loop.asm
  src/crypto/cn/asm/win64/cn1/cnv1_double_main_loop.inc
  src/crypto/cn/asm/win64/cn1/cnv1_quad_main_loop.inc
  src/crypto/cn/asm/win64/cn1/cnv1_single_main_loop.inc
  src/crypto/cn/asm/win64/cn_main_loop.S
  src/crypto/cn/asm/win64/cn_main_loop.asm
  src/crypto/ghostrider/CMakeLists.txt
  src/crypto/ghostrider/README.md
Labels: algo

#2772 Compilation fixes
  src/crypto/cn/CnHash.cpp
  src/crypto/cn/CryptoNight_x86.h
  src/crypto/randomx/randomx.cpp
Labels: bug

#2778 Fixed "READY threads X/X" display after algo switching
  src/backend/cpu/CpuBackend.cpp
Labels: bug

#2782 Updated GhostRider documentation
  scripts/rtm_ghostrider_example.cmd
  src/crypto/ghostrider/README.md
Labels: algo

#2815 Fixed cn-heavy in 32-bit builds
  src/crypto/cn/CryptoNight_x86.h
Labels: bug, algo

#2827 GhostRider: set correct priority for helper threads
  src/backend/cpu/CpuWorker.cpp
  src/crypto/ghostrider/ghostrider.cpp
  src/crypto/ghostrider/ghostrider.h
Labels: bug

#2837 RandomX: don't restart mining threads when the seed changes
  src/backend/cpu/CpuWorker.cpp
  src/core/Miner.cpp
  src/crypto/rx/RxQueue.cpp
Labels: enhancement

#2848 Add support for client.reconnect method
  src/base/net/stratum/Client.cpp
  src/base/net/stratum/Client.h
  src/base/net/stratum/Pool.h
Labels: bug
