Repository xmrig/xmrig, pull requests merged in 2021-09, with the labels that each got.

#2582 Fixup RandomX naming consistency
  src/crypto/randomx/jit_compiler_x86.cpp
  src/crypto/randomx/randomx.cpp
  src/crypto/randomx/randomx.h
Labels: randomx

#2586 Fixed Windows 7 compatibility
  src/base/io/Env.cpp
Labels: bug

#2591 Fix compile warning/crash when WITH_RANDOMX=OFF
  src/backend/cpu/CpuWorker.cpp
Labels: bug

#2594 Added Windows taskbar icon colors
  CMakeLists.txt
  src/core/Miner.cpp
  src/core/Taskbar.cpp
  src/core/Taskbar.h
Labels: enhancement

#2606 Fix: AstroBWT auto-config ignored max-threads-hint
  src/backend/cpu/platform/HwlocCpuInfo.cpp
Labels: bug
