Repository xmrig/xmrig, pull requests merged in 2021-11, with the labels that each got.

#2627 fix: expand validation of tx_extra for merge mining tag
  src/base/net/stratum/SelfSelectClient.cpp
  src/base/tools/cryptonote/BlockTemplate.cpp
  src/base/tools/cryptonote/BlockTemplate.h
Labels: bug

#2682 Fix: use cn-heavy optimization only for Vermeer CPUs
  src/backend/cpu/CpuWorker.cpp
  src/backend/cpu/interfaces/ICpuInfo.h
  src/backend/cpu/platform/BasicCpuInfo.h
Labels: bug

#2684 MSR mod: fix for error 183
  src/hw/msr/Msr_win.cpp
Labels: bug

#2713 Optimized quad hash for Ryzens
  src/crypto/cn/CryptoNight_x86.h
Labels: algo

#2714 GhostRider: fixed invalid hashes on ARMv8
  src/crypto/ghostrider/ghostrider.cpp
Labels: algo

#2715 Benchmark support for GhostRider (offline only)
  src/base/kernel/interfaces/IConfig.h
  src/base/net/stratum/benchmark/BenchClient.cpp
  src/base/net/stratum/benchmark/BenchConfig.cpp
  src/base/net/stratum/benchmark/BenchConfig.h
  src/core/config/ConfigTransform.cpp
  src/core/config/Config_platform.h
Labels: algo

#2716 Only initGhostRider() when job is in the family
  src/core/Miner.cpp
Labels: algo

#2719 Added GhostRider release notes
  CHANGELOG.md
  CMakeLists.txt
  scripts/rtm_ghostrider_example.cmd
  src/crypto/ghostrider/README.md
Labels: algo

#2729 GhostRider hotfixes
  src/backend/common/Hashrate.cpp
  src/backend/common/Hashrate.h
  src/backend/common/Worker.h
  src/backend/common/interfaces/IWorker.h
  src/backend/cpu/CpuBackend.cpp
  src/backend/cpu/CpuLaunchData.cpp
  src/backend/cpu/CpuWorker.h
  src/base/crypto/Algorithm.h
  src/core/Miner.cpp
  src/crypto/ghostrider/README.md
Labels: bug, algo

#2738 More GhostRider fixes
  src/base/base.cmake
  src/base/net/stratum/EthStratumClient.cpp
  src/base/net/stratum/Pool.cpp
Labels: bug

#2740 Added VAES support for Cryptonight variants
  CHANGELOG.md
  CMakeLists.txt
  src/backend/cpu/CpuWorker.cpp
  src/backend/cpu/interfaces/ICpuInfo.h
  src/backend/cpu/platform/BasicCpuInfo.cpp
  src/backend/cpu/platform/BasicCpuInfo.h
  src/crypto/cn/CnHash.cpp
  src/crypto/cn/CryptoNight_test.h
  src/crypto/cn/CryptoNight_x86.h
  src/crypto/cn/CryptoNight_x86_vaes.cpp
  src/crypto/cn/CryptoNight_x86_vaes.h
  src/crypto/ghostrider/README.md
  src/crypto/ghostrider/ghostrider.cpp
  src/crypto/ghostrider/ghostrider.h
Labels: algo

#2746 Fix compile for VAES support with GCC<10
  src/crypto/cn/CryptoNight_x86_vaes.cpp
Labels: bug

#2747 Disable VAES in 32-bit builds
  CMakeLists.txt
  cmake/cpu.cmake
  src/crypto/cn/CryptoNight_x86.h
Labels: bug

#2751 VAES crash fixes
  src/backend/cpu/platform/BasicCpuInfo.cpp
  src/crypto/cn/CryptoNight_x86_vaes.cpp
  src/crypto/ghostrider/ghostrider.cpp
Labels: bug
