Repository xmrig/xmrig, pull requests merged in 2021-04, with the labels that each got.

#2225 Add missing include
  src/backend/common/Workers.h
Labels: bug

#2229 Don't use RandomX JIT if WITH_ASM=OFF
  cmake/randomx.cmake
  src/crypto/randomx/common.hpp
  src/crypto/randomx/jit_compiler.hpp
  src/crypto/randomx/randomx.cpp
Labels: bug

#2228 remove useless v4_random_math_init if algo is not cn/r
  src/crypto/cn/CryptoNight_monero.h
Labels: bug

#2233 Fixed compilation for ARM
  cmake/randomx.cmake
  src/crypto/randomx/common.hpp
  src/crypto/randomx/jit_compiler.hpp
  src/crypto/randomx/randomx.cpp
Labels: arm, bug

#2235 Fixed cn-heavy for GCC-8
  src/crypto/cn/CryptoNight_x86.h
Labels: bug

#2234 fix build error on gcc 4.8.5
  src/base/io/log/FileLogWriter.cpp
  src/base/io/log/FileLogWriter.h
Labels: bug

#2239 Fixed broken "coin" setting functionality
  src/base/net/stratum/Client.cpp
  src/base/net/stratum/DaemonClient.cpp
  src/base/net/stratum/SelfSelectClient.cpp
Labels: bug

#2261 Show total hashrate if compiled without OpenCL
  src/backend/cpu/CpuBackend.cpp
Labels: bug

#2276 Added support for Uplexa (cn/upx2 algorithm)
  CMakeLists.txt
  src/backend/cpu/CpuConfig.cpp
  src/backend/cpu/CpuConfig_gen.h
  src/backend/cpu/CpuWorker.cpp
  src/backend/cpu/platform/BasicCpuInfo.cpp
  src/backend/cpu/platform/HwlocCpuInfo.cpp
  src/backend/cuda/CudaConfig.cpp
  src/backend/cuda/CudaConfig_gen.h
  src/backend/opencl/OclConfig.cpp
  src/backend/opencl/OclConfig_gen.h
  src/backend/opencl/cl/cn/algorithm.cl
  src/backend/opencl/cl/cn/cryptonight.cl
  src/backend/opencl/cl/cn/cryptonight_cl.h
  src/backend/opencl/cl/rx/randomx_cl.h
  src/backend/opencl/generators/ocl_vega_cn_generator.cpp
  src/backend/opencl/runners/OclCnRunner.cpp
  src/base/crypto/Algorithm.cpp
  src/base/crypto/Algorithm.h
  src/crypto/cn/CnAlgo.h
  src/crypto/cn/CnHash.cpp
  src/crypto/cn/CryptoNight_arm.h
  src/crypto/cn/CryptoNight_test.h
  src/crypto/cn/CryptoNight_x86.h
Labels: algo

#2278 Optimized cn/upx2
  src/crypto/cn/CnHash.cpp
  src/crypto/cn/CryptoNight_x86.h
  src/crypto/cn/asm/cn2/cnv2_upx_double_mainloop_zen3.inc
  src/crypto/cn/asm/cn_main_loop.S
  src/crypto/cn/asm/cn_main_loop.asm
  src/crypto/cn/asm/win64/cn2/cnv2_upx_double_mainloop_zen3.inc
  src/crypto/cn/asm/win64/cn_main_loop.S
  src/crypto/cn/asm/win64/cn_main_loop.asm
Labels: algo

#2287 Fixed rounding mode after running cn/upx
  src/crypto/cn/asm/cn2/cnv2_upx_double_mainloop_zen3.inc
  src/crypto/cn/asm/win64/cn2/cnv2_upx_double_mainloop_zen3.inc
  src/crypto/common/HugePagesInfo.h
Labels: algo, bug

#2289 RandomX: optimized IMUL_RCP instruction
  src/crypto/randomx/asm/program_imul_rcp_store.inc
  src/crypto/randomx/jit_compiler_x86.cpp
  src/crypto/randomx/jit_compiler_x86.hpp
  src/crypto/randomx/jit_compiler_x86_static.S
  src/crypto/randomx/jit_compiler_x86_static.asm
  src/crypto/randomx/jit_compiler_x86_static.hpp
Labels: randomx

#2296 Fixed Zen3 asm for cn/upx2
  src/crypto/cn/CryptoNight_x86.h
  src/crypto/cn/asm/cn2/cnv2_upx_double_mainloop_zen3.inc
  src/crypto/cn/asm/win64/cn2/cnv2_upx_double_mainloop_zen3.inc
Labels: algo, bug

#2312 Add missing allow_writes=on to randomx_boost.sh
  scripts/randomx_boost.sh
Labels: bug

#2322 Update randomx_boost.sh
  scripts/randomx_boost.sh
Labels: enhancement
