Repository xmrig/xmrig, pull requests merged in 2022-01, with the labels that each got.

#2856 Fix for short responses from some Raptoreum pools
  src/base/net/stratum/Client.cpp
Labels: bug

#2873 Fixed GhostRider benchmark on single-core systems
  src/crypto/ghostrider/ghostrider.cpp
Labels: bug

#2882 armv7 compilation fix
  src/crypto/cn/sse2neon.h
Labels: bug, arm

#2893 KawPow OpenCL: use separate UV loop for building programs
  src/backend/opencl/runners/tools/OclKawPow.cpp
Labels: bug, opencl

#2904 Fixed unaligned memory accesses
  src/backend/common/WorkerJob.h
  src/backend/cpu/CpuWorker.cpp
  src/backend/cuda/CudaWorker.cpp
  src/backend/opencl/OclWorker.cpp
  src/base/base.cmake
  src/base/net/stratum/Job.cpp
  src/base/tools/Alignment.h
  src/crypto/common/Nonce.cpp
  src/net/JobResult.h
Labels: bug, arm

#2898 Fixed armv7 compilation
  cmake/flags.cmake
Labels: bug, arm
