Repository xmrig/xmrig, pull requests merged in 2023-06, with the labels that each got.

#3236 fix(cuda): receive CUDA loader error on linux too.
  src/backend/cuda/wrappers/CudaLib.cpp
Labels: bug, CUDA

#3288 KawPow: fixed data race when building programs
  src/backend/opencl/runners/tools/OclKawPow.cpp
Labels: bug

#3290 Zephyr coin support
  src/base/crypto/Coin.cpp
  src/base/crypto/Coin.h
  src/base/tools/cryptonote/BlockTemplate.cpp
Labels: enhancement, algo

#3291 Zephyr solo mining: fix for blocks with transactions
  src/base/tools/cryptonote/BlockTemplate.cpp
Labels: algo
