Repository xmrig/xmrig, pull requests merged in 2025-06, with the labels that each got.

#3666 Better detection of aligned malloc functions
  cmake/randomx.cmake
  src/crypto/randomx/intrin_portable.h
Labels: randomx

#3671 Hwloc: fixed detection of L2 cache size for some complex NUMA topologies
  src/backend/cpu/platform/HwlocCpuInfo.cpp
Labels: bug, randomx

#3674 cflags: Add lax-vector-conversions on ARMv7
  cmake/flags.cmake
Labels: bug, arm

#3678 Improved IPv6 support.
  src/base/kernel/config/BaseTransform.cpp
  src/base/kernel/interfaces/IConfig.h
  src/base/kernel/interfaces/IDnsBackend.h
  src/base/net/dns/Dns.cpp
  src/base/net/dns/Dns.h
  src/base/net/dns/DnsConfig.cpp
  src/base/net/dns/DnsConfig.h
  src/base/net/dns/DnsRecord.cpp
  src/base/net/dns/DnsRecord.h
  src/base/net/dns/DnsRecords.cpp
  src/base/net/dns/DnsRecords.h
  src/base/net/dns/DnsRequest.h
  src/base/net/dns/DnsUvBackend.cpp
  src/base/net/dns/DnsUvBackend.h
  src/config.json
  src/core/config/Config_platform.h
  src/core/config/usage.h
Labels: enhancement

#3680 Add armv8l to list of 32 bit ARM targets
  cmake/cpu.cmake
Labels: bug, arm
